# Generated by Django 3.1.1 on 2020-10-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200922_1847'),
        ('carts', '0008_auto_20201010_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
