# Generated by Django 3.1.1 on 2020-10-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
