# Generated by Django 3.1.1 on 2020-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_remove_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(),
        ),
    ]
