# Generated by Django 3.1.1 on 2020-09-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profiles', '0002_auto_20200927_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
    ]
