# Generated by Django 3.1.1 on 2020-09-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_profiles', '0002_auto_20200927_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='billing', max_length=50)),
                ('house_number', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=200)),
                ('barangay', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('country', models.CharField(default='Philippines', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_profiles.customerprofile')),
            ],
        ),
    ]
