# Generated by Django 3.1.1 on 2020-09-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200927_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'CASH ON DELIVERY'), ('paypal', 'PAYPAL')], default='cod', max_length=20),
        ),
    ]
