# Generated by Django 3.1.1 on 2020-10-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201010_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.FloatField(),
        ),
    ]
