# Generated by Django 3.0.4 on 2020-09-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2000000)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('category', models.CharField(choices=[('none', 'None'), ('shirt', 'Shirt'), ('dress', 'Dress'), ('shoes', 'Shoes'), ('phone', 'Phone'), ('laptop', 'Laptop'), ('accessories', 'Accessories')], default='none', max_length=100)),
                ('label', models.CharField(choices=[('none', 'NONE'), ('new', 'NEW'), ('hot', 'HOT'), ('special', 'SPECIAL'), ('best_seller', 'BEST SELLER')], default='none', max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, default='default_product_image.jpg', upload_to='products')),
                ('image2', models.ImageField(blank=True, default='default_product_image.jpg', upload_to='products')),
                ('image3', models.ImageField(blank=True, default='default_product_image.jpg', upload_to='products')),
                ('image4', models.ImageField(blank=True, default='default_product_image.jpg', upload_to='products')),
            ],
        ),
    ]
