# Generated by Django 3.1.1 on 2020-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201010_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('dress', 'Dress'), ('shoes', 'Shoes'), ('phone', 'Phone'), ('laptop', 'Laptop'), ('accessories', 'Accessories')], default='none', max_length=100),
        ),
    ]
