# Generated by Django 3.1.1 on 2020-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('accesories', 'Accessories')], default='none', max_length=100),
        ),
    ]
